CREATE TABLE `user` (
 `num` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 `id` VARCHAR(20) NOT NULL,
 `password` VARCHAR(20) NOT NULL,
 `nickname` VARCHAR(20) NOT NULL,
 `Q1` VARCHAR(20) NOT NULL,
 `Q2` VARCHAR(20) NOT NULL
 );